version: '3.8'

services:
  tarefy-maker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
        - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}
        - REACT_APP_GEMINI_API_KEY=${REACT_APP_GEMINI_API_KEY}
        - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}
      - REACT_APP_GEMINI_API_KEY=${REACT_APP_GEMINI_API_KEY}
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tarefy-network

networks:
  tarefy-network:
    driver: bridge
